In [13]:
import math
import numpy as np

In [20]:
import pandas as pd

In [14]:
fA = np.array([[7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])
fA

array([[ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [15]:
fB = np.array(
    [
        [5, 13, 19, 14, 42, 49, 46, 67, 64, 32, 12, 4],
        [8, 17, 28, 39, 66, 71, 74, 154, 126, 57, 20, 7],
        [2, 8, 15, 24, 14, 51, 48, 68, 145, 55, 11, 2],
    ]
)

fB

array([[  5,  13,  19,  14,  42,  49,  46,  67,  64,  32,  12,   4],
       [  8,  17,  28,  39,  66,  71,  74, 154, 126,  57,  20,   7],
       [  2,   8,  15,  24,  14,  51,  48,  68, 145,  55,  11,   2]])

In [16]:
fC = np.concatenate((fA, fB), axis=0).T
fC

array([[  7,   5,   8,   2],
       [  8,  13,  17,   8],
       [  9,  19,  28,  15],
       [ 10,  14,  39,  24],
       [ 11,  42,  66,  14],
       [ 12,  49,  71,  51],
       [ 13,  46,  74,  48],
       [ 14,  67, 154,  68],
       [ 15,  64, 126, 145],
       [ 16,  32,  57,  55],
       [ 17,  12,  20,  11],
       [ 18,   4,   7,   2]])

#task 1D = 289

In [51]:
fC[(fC[:, 0] == 14)][:,1:].sum()

289

In [27]:
dF = pd.DataFrame(
    {
        "Time": list(range(7, 19)),
        "Floor1": [5, 13, 19, 14, 42, 49, 46, 67, 64, 32, 12, 4],
        "Floor2": [8, 17, 28, 39, 66, 71, 74, 154, 126, 57, 20, 7],
        "Floor3": [2, 8, 15, 24, 14, 51, 48, 68, 145, 55, 11, 2],
    }
)
dF

Time  Floor1  Floor2  Floor3
0      7       5       8       2
1      8      13      17       8
2      9      19      28      15
3     10      14      39      24
4     11      42      66      14
5     12      49      71      51
6     13      46      74      48
7     14      67     154      68
8     15      64     126     145
9     16      32      57      55
10    17      12      20      11
11    18       4       7       2

In [32]:
dF[dF["Time"] == 14][["Floor1", "Floor2", "Floor3"]].values.sum()

289

In [47]:
fC[((fC[:, 0] >= 7) & (fC[:,0]<=18))][:,-1].sum()

443

In [41]:
fC[((fC[:, 0] >= 12) & (fC[:,0]<=18))][:,1:].sum()

1163