In [4]:
import numpy as np

In [5]:
np.arange(1, 20, 1.8, dtype=float)

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. , 11.8, 13.6, 15.4, 17.2, 19. ])

In [6]:
np.arange(0, 2*np.pi, np.pi/10, dtype=float)

array([0.        , 0.31415927, 0.62831853, 0.9424778 , 1.25663706,
       1.57079633, 1.88495559, 2.19911486, 2.51327412, 2.82743339,
       3.14159265, 3.45575192, 3.76991118, 4.08407045, 4.39822972,
       4.71238898, 5.02654825, 5.34070751, 5.65486678, 5.96902604])

In [7]:
np.linspace(4,20,15)

array([ 4.        ,  5.14285714,  6.28571429,  7.42857143,  8.57142857,
        9.71428571, 10.85714286, 12.        , 13.14285714, 14.28571429,
       15.42857143, 16.57142857, 17.71428571, 18.85714286, 20.        ])